import ErdosProblems1066.Swanepoel.UniformFiniteGeometryRowsSourceW29

set_option autoImplicit false
set_option linter.unusedDecidableInType false

/-!
# W30 Lemma 8 frame/cyclic-order rows

This file sharpens the W29 uniform finite-geometry row surface to the
row-level data actually needed at each minimal failure: the frame/cardinality
row together with the neighbor-cyclic-order row for the generated extra
neighbors.
-/

namespace ErdosProblems1066
namespace Swanepoel
namespace FrameCyclicOrderRowsW30

open Lemma8NeighborExtractionConcrete
open MinimalGraphFacts
open PointwiseFamilyProducerW18

universe u

noncomputable section

variable
  (payForCut : PayForCutConcreteProducerFamily)
  (topologyArc : TopologyArcConcreteProducerFamily.{u})

abbrev UniformFiniteGeometryRows : Type (u + 1) :=
  UniformFiniteGeometryRowsSourceW29.UniformFiniteGeometryRows.{u}
    payForCut topologyArc

abbrev FiniteGeometryRows
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C) : Type :=
  UniformFiniteGeometryRowsSourceW29.FiniteGeometryRows.{u}
    payForCut topologyArc C hmin

abbrev FrameRows : Prop :=
  UniformFiniteGeometryRowsSourceW29.FrameRows.{u}
    payForCut topologyArc

abbrev FrameCardinalityRow
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C) : Prop :=
  UniformFiniteGeometryRowsSourceW29.FrameCardinalityRow.{u}
    payForCut topologyArc C hmin

abbrev NeighborCyclicOrderRow
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C)
    (R : FrameCardinalityRow.{u} payForCut topologyArc C hmin) : Type :=
  UniformFiniteGeometryRowsSourceW29.NeighborCyclicOrderRow.{u}
    payForCut topologyArc C hmin R

abbrev NeighborCyclicOrderRowsForFrameRows
    (frameRows : FrameRows.{u} payForCut topologyArc) :=
  UniformFiniteGeometryRowsSourceW29.NeighborCyclicOrderRowsForFrameRows.{u}
    payForCut topologyArc frameRows

abbrev DegreeSixNoncyclicRows : Prop :=
  UniformFiniteGeometryRowsSourceW29.DegreeSixNoncyclicRows.{u}
    payForCut topologyArc

abbrev DegreeSixNeighborCyclicOrderRows : Type (u + 1) :=
  UniformFiniteGeometryRowsSourceW29.DegreeSixNeighborCyclicOrderRows.{u}
    payForCut topologyArc

/-- One pointwise row: frame/cardinality data plus the cyclic order for the
extra-neighbor data generated by that row. -/
structure FrameCyclicOrderRow
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C) : Type where
  frameCardinality :
    FrameCardinalityRow.{u} payForCut topologyArc C hmin
  neighborCyclicOrder :
    NeighborCyclicOrderRow.{u}
      payForCut topologyArc C hmin frameCardinality

def finiteGeometryRowsOfFrameCyclicOrderRow
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C)
    (P : FrameCyclicOrderRow.{u} payForCut topologyArc C hmin) :
    FiniteGeometryRows.{u} payForCut topologyArc C hmin where
  frameCardinality := P.frameCardinality
  positiveOrder :=
    Lemma8FiniteGeometryRowsW28.positiveOrderRowOfNeighborCyclicOrderRow
      (payForCut := payForCut) (topologyArc := topologyArc)
      C hmin P.neighborCyclicOrder

def frameCyclicOrderRowOfFiniteGeometryRows
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C)
    (P : FiniteGeometryRows.{u} payForCut topologyArc C hmin) :
    FrameCyclicOrderRow.{u} payForCut topologyArc C hmin where
  frameCardinality := P.frameCardinality
  neighborCyclicOrder :=
    Lemma8FiniteGeometryRowsW28.neighborCyclicOrderRowOfPositiveOrderRow
      (payForCut := payForCut) (topologyArc := topologyArc)
      C hmin P.positiveOrder

theorem finiteGeometryRows_nonempty_iff_frameCyclicOrderRow
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C) :
    Nonempty (FiniteGeometryRows.{u} payForCut topologyArc C hmin) <->
      Nonempty
        (FrameCyclicOrderRow.{u} payForCut topologyArc C hmin) := by
  constructor
  case mp =>
    intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (frameCyclicOrderRowOfFiniteGeometryRows
              (payForCut := payForCut) (topologyArc := topologyArc)
              C hmin P)
  case mpr =>
    intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (finiteGeometryRowsOfFrameCyclicOrderRow
              (payForCut := payForCut) (topologyArc := topologyArc)
              C hmin P)

/-- Uniform pointwise frame/cyclic-order rows for every minimal failure. -/
structure UniformFrameCyclicOrderRows : Type (u + 1) where
  row :
    forall {n : Nat} (C : _root_.UDConfig n)
      (hmin : IsMinimalClearedFailure C),
        FrameCyclicOrderRow.{u} payForCut topologyArc C hmin

def uniformRowsOfUniformFrameCyclicOrderRows
    (P : UniformFrameCyclicOrderRows.{u} payForCut topologyArc) :
    UniformFiniteGeometryRows.{u} payForCut topologyArc where
  row := fun C hmin =>
    finiteGeometryRowsOfFrameCyclicOrderRow
      (payForCut := payForCut) (topologyArc := topologyArc)
      C hmin (P.row C hmin)

def uniformFrameCyclicOrderRowsOfUniformRows
    (P : UniformFiniteGeometryRows.{u} payForCut topologyArc) :
    UniformFrameCyclicOrderRows.{u} payForCut topologyArc where
  row := fun C hmin =>
    frameCyclicOrderRowOfFiniteGeometryRows
      (payForCut := payForCut) (topologyArc := topologyArc)
      C hmin (P.row C hmin)

theorem uniformFiniteGeometryRows_nonempty_iff_uniformFrameCyclicOrderRows :
    Nonempty (UniformFiniteGeometryRows.{u} payForCut topologyArc) <->
      Nonempty
        (UniformFrameCyclicOrderRows.{u} payForCut topologyArc) := by
  constructor
  case mp =>
    intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (uniformFrameCyclicOrderRowsOfUniformRows
              (payForCut := payForCut) (topologyArc := topologyArc) P)
  case mpr =>
    intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (uniformRowsOfUniformFrameCyclicOrderRows
              (payForCut := payForCut) (topologyArc := topologyArc) P)

def frameRowsOfUniformFrameCyclicOrderRows
    (P : UniformFrameCyclicOrderRows.{u} payForCut topologyArc) :
    FrameRows.{u} payForCut topologyArc :=
  fun C hmin => (P.row C hmin).frameCardinality

def neighborCyclicOrderRowsOfUniformFrameCyclicOrderRows
    (P : UniformFrameCyclicOrderRows.{u} payForCut topologyArc) :
    NeighborCyclicOrderRowsForFrameRows.{u}
      payForCut topologyArc
      (frameRowsOfUniformFrameCyclicOrderRows
        (payForCut := payForCut) (topologyArc := topologyArc) P) :=
  fun C hmin => (P.row C hmin).neighborCyclicOrder

def uniformFrameCyclicOrderRowsOfFrameRowsNeighborCyclicOrderRows
    (frameRows : FrameRows.{u} payForCut topologyArc)
    (orderRows :
      NeighborCyclicOrderRowsForFrameRows.{u}
        payForCut topologyArc frameRows) :
    UniformFrameCyclicOrderRows.{u} payForCut topologyArc where
  row := fun C hmin =>
    { frameCardinality := frameRows C hmin
      neighborCyclicOrder := orderRows C hmin }

theorem uniformFrameCyclicOrderRows_nonempty_iff_frameRows_neighborCyclicOrderRows :
    Nonempty
        (UniformFrameCyclicOrderRows.{u} payForCut topologyArc) <->
      exists frameRows : FrameRows.{u} payForCut topologyArc,
        Nonempty
          (NeighborCyclicOrderRowsForFrameRows.{u}
            payForCut topologyArc frameRows) := by
  constructor
  case mp =>
    intro h
    cases h with
    | intro P =>
        exact
          Exists.intro
            (frameRowsOfUniformFrameCyclicOrderRows
              (payForCut := payForCut) (topologyArc := topologyArc) P)
            (Nonempty.intro
              (neighborCyclicOrderRowsOfUniformFrameCyclicOrderRows
                (payForCut := payForCut) (topologyArc := topologyArc) P))
  case mpr =>
    intro h
    cases h with
    | intro frameRows horders =>
        cases horders with
        | intro orderRows =>
            exact
              Nonempty.intro
                (uniformFrameCyclicOrderRowsOfFrameRowsNeighborCyclicOrderRows
                  (payForCut := payForCut) (topologyArc := topologyArc)
                  frameRows orderRows)

theorem uniformFiniteGeometryRows_nonempty_iff_frameRows_neighborCyclicOrderRows :
    Nonempty (UniformFiniteGeometryRows.{u} payForCut topologyArc) <->
      exists frameRows : FrameRows.{u} payForCut topologyArc,
        Nonempty
          (NeighborCyclicOrderRowsForFrameRows.{u}
            payForCut topologyArc frameRows) := by
  exact
    (uniformFiniteGeometryRows_nonempty_iff_uniformFrameCyclicOrderRows
      (payForCut := payForCut) (topologyArc := topologyArc)).trans
      (uniformFrameCyclicOrderRows_nonempty_iff_frameRows_neighborCyclicOrderRows
        (payForCut := payForCut) (topologyArc := topologyArc))

def frameRowsOfDegreeSixNoncyclicRows
    (degreeRows : DegreeSixNoncyclicRows.{u} payForCut topologyArc) :
    FrameRows.{u} payForCut topologyArc :=
  Lemma8FrameRowsInhabitationW25.frameRowsOfDegreeSixNoncyclicRows
    (payForCut := payForCut) (topologyArc := topologyArc) degreeRows

/-- The degree-six route also needs the cyclic order keyed to the frame rows
generated from the degree-six/non-cyclic rows. -/
abbrev DegreeSixGeneratedFrameCyclicRows : Prop :=
  exists degreeRows : DegreeSixNoncyclicRows.{u} payForCut topologyArc,
    Nonempty
      (NeighborCyclicOrderRowsForFrameRows.{u}
        payForCut topologyArc
        (frameRowsOfDegreeSixNoncyclicRows
          (payForCut := payForCut) (topologyArc := topologyArc)
          degreeRows))

def degreeSixNeighborCyclicOrderRowsOfGeneratedFrameCyclicRows
    (degreeRows : DegreeSixNoncyclicRows.{u} payForCut topologyArc)
    (orderRows :
      NeighborCyclicOrderRowsForFrameRows.{u}
        payForCut topologyArc
        (frameRowsOfDegreeSixNoncyclicRows
          (payForCut := payForCut) (topologyArc := topologyArc)
          degreeRows)) :
    DegreeSixNeighborCyclicOrderRows.{u} payForCut topologyArc where
  degreeRows := degreeRows
  neighborCyclicOrderRows := orderRows

theorem degreeSixNeighborCyclicOrderRows_nonempty_iff_generatedFrameCyclicRows :
    Nonempty
        (DegreeSixNeighborCyclicOrderRows.{u} payForCut topologyArc) <->
      DegreeSixGeneratedFrameCyclicRows.{u} payForCut topologyArc := by
  constructor
  case mp =>
    intro h
    cases h with
    | intro P =>
        exact
          Exists.intro P.degreeRows
            (Nonempty.intro P.neighborCyclicOrderRows)
  case mpr =>
    intro h
    cases h with
    | intro degreeRows horders =>
        cases horders with
        | intro orderRows =>
            exact
              Nonempty.intro
                (degreeSixNeighborCyclicOrderRowsOfGeneratedFrameCyclicRows
                  (payForCut := payForCut) (topologyArc := topologyArc)
                  degreeRows orderRows)

def uniformFrameCyclicOrderRowsOfDegreeSixNeighborCyclicOrderRows
    (P : DegreeSixNeighborCyclicOrderRows.{u} payForCut topologyArc) :
    UniformFrameCyclicOrderRows.{u} payForCut topologyArc :=
  uniformFrameCyclicOrderRowsOfFrameRowsNeighborCyclicOrderRows
    (payForCut := payForCut) (topologyArc := topologyArc)
    (frameRowsOfDegreeSixNoncyclicRows
      (payForCut := payForCut) (topologyArc := topologyArc)
      P.degreeRows)
    P.neighborCyclicOrderRows

theorem uniformFrameCyclicOrderRows_nonempty_of_degreeSixNeighborCyclicOrderRows
    (P : DegreeSixNeighborCyclicOrderRows.{u} payForCut topologyArc) :
    Nonempty
      (UniformFrameCyclicOrderRows.{u} payForCut topologyArc) :=
  Nonempty.intro
    (uniformFrameCyclicOrderRowsOfDegreeSixNeighborCyclicOrderRows
      (payForCut := payForCut) (topologyArc := topologyArc) P)

theorem uniformFiniteGeometryRows_nonempty_of_degreeSixGeneratedFrameCyclicRows
    (h : DegreeSixGeneratedFrameCyclicRows.{u} payForCut topologyArc) :
    Nonempty (UniformFiniteGeometryRows.{u} payForCut topologyArc) := by
  have hdegree :
      Nonempty
        (DegreeSixNeighborCyclicOrderRows.{u} payForCut topologyArc) :=
    (degreeSixNeighborCyclicOrderRows_nonempty_iff_generatedFrameCyclicRows
      (payForCut := payForCut) (topologyArc := topologyArc)).2 h
  cases hdegree with
  | intro P =>
      exact
        UniformFiniteGeometryRowsSourceW29.uniformFiniteGeometryRows_nonempty_of_degreeSixNeighborCyclicOrderRows
          (payForCut := payForCut) (topologyArc := topologyArc)
          P

end

end FrameCyclicOrderRowsW30
end Swanepoel

namespace Verified

universe u

abbrev SwanepoelW30Lemma8UniformFrameCyclicOrderRows
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u}) :
    Type (u + 1) :=
  Swanepoel.FrameCyclicOrderRowsW30.UniformFrameCyclicOrderRows.{u}
    payForCut topologyArc

abbrev SwanepoelW30Lemma8DegreeSixGeneratedFrameCyclicRows
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u}) :
    Prop :=
  Swanepoel.FrameCyclicOrderRowsW30.DegreeSixGeneratedFrameCyclicRows.{u}
    payForCut topologyArc

theorem swanepoel_w30_lemma8UniformFiniteGeometryRows_nonempty_iff_uniformFrameCyclicOrderRows
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u}) :
    Nonempty
        (Swanepoel.UniformFiniteGeometryRowsSourceW29.UniformFiniteGeometryRows.{u}
          payForCut topologyArc) <->
      Nonempty
        (SwanepoelW30Lemma8UniformFrameCyclicOrderRows.{u}
          payForCut topologyArc) :=
  Swanepoel.FrameCyclicOrderRowsW30.uniformFiniteGeometryRows_nonempty_iff_uniformFrameCyclicOrderRows
    (payForCut := payForCut) (topologyArc := topologyArc)

theorem swanepoel_w30_lemma8DegreeSixNeighborCyclicOrderRows_nonempty_iff_generatedFrameCyclicRows
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u}) :
    Nonempty
        (Swanepoel.UniformFiniteGeometryRowsSourceW29.DegreeSixNeighborCyclicOrderRows.{u}
          payForCut topologyArc) <->
      SwanepoelW30Lemma8DegreeSixGeneratedFrameCyclicRows.{u}
        payForCut topologyArc :=
  Swanepoel.FrameCyclicOrderRowsW30.degreeSixNeighborCyclicOrderRows_nonempty_iff_generatedFrameCyclicRows
    (payForCut := payForCut) (topologyArc := topologyArc)

end Verified
end ErdosProblems1066
