import ErdosProblems1066.Swanepoel.Lemma8ProducerFamilyW20
import ErdosProblems1066.Swanepoel.PointwiseProducerFamilyFieldsW20
import ErdosProblems1066.Swanepoel.RemainingObligationLedgerW20

set_option autoImplicit false
set_option linter.unusedDecidableInType false

/-!
# W21 Lemma 8 source inhabitation audit

The W19/W20 interfaces reduce the Lemma 8 geometry source family to two
pointwise fields:

* the reduced frame/cardinality payload from `BoundaryFrameCoreProducerW19`;
* the positive cyclic-order certificate from `PositiveCyclicOrderProducerW19`.

This file proves that this package is exact for the W20 Lemma 8 geometry
source family consumed by both `PointwiseProducerFamilyFieldsW20` and
`RemainingObligationLedgerW20`.  It does not add any geometric existence
principle; the final inhabitance statement is conditional on precisely those
two remaining families.
-/

namespace ErdosProblems1066
namespace Swanepoel
namespace Lemma8SourceInhabitationW21

open BoundaryFrameCoreProducerW19
open Lemma8ConcreteGeometryProducerW19
open Lemma8ProducerFamilyW20
open MinimalGraphFacts
open PointwiseFamilyProducerW18
open PositiveCyclicOrderProducerW19

universe u

noncomputable section

variable
  (payForCut : PayForCutConcreteProducerFamily)
  (topologyArc : TopologyArcConcreteProducerFamily.{u})

/-- The Lemma 8 geometry source family in the spelling used by
`PointwiseProducerFamilyFieldsW20`. -/
abbrev PointwiseW20Lemma8SourceFamily : Type (u + 1) :=
  PointwiseProducerFamilyFieldsW20.Lemma8GeometrySourceFamily.{u}
    payForCut topologyArc

/-- The Lemma 8 geometry source family in the spelling used by
`RemainingObligationLedgerW20`. -/
abbrev LedgerW20Lemma8SourceFamily : Type (u + 1) :=
  RemainingObligationLedgerW20.Lemma8GeometryFieldFamily.{u}
    payForCut topologyArc

/-- The exact remaining W20 package: frame/cardinality rows together with
positive cyclic-order rows for the neighbors generated by those rows. -/
abbrev ExactLemma8SourceRemainingPackage : Type (u + 1) :=
  Lemma8ProducerFamilyW20.PointwiseLemma8RemainingFieldPackage.{u}
    payForCut topologyArc

/-- Build the pointwise W20 Lemma 8 source family from exactly the W19
frame/cardinality and positive-order families. -/
def pointwiseSourceFamilyOfExactPackage
    (P : ExactLemma8SourceRemainingPackage.{u} payForCut topologyArc) :
    PointwiseW20Lemma8SourceFamily.{u} payForCut topologyArc :=
  P.toPointwiseLemma8GeometryFieldFamily

/-- The same construction in the `RemainingObligationLedgerW20` spelling. -/
def ledgerSourceFamilyOfExactPackage
    (P : ExactLemma8SourceRemainingPackage.{u} payForCut topologyArc) :
    LedgerW20Lemma8SourceFamily.{u} payForCut topologyArc :=
  P.toPointwiseLemma8GeometryFieldFamily

/-- Extract the reduced frame/cardinality row from a full finite Lemma 8
geometry row. -/
def frameCoreRowOfGeometryRow
    {n : Nat} {C : _root_.UDConfig n}
    {hmin : IsMinimalClearedFailure C}
    (G :
      PointwiseLemma8GeometryFields.{u}
        payForCut topologyArc C hmin) :
    M8FrameCoreCardinalitySources
      (pointwiseSpine payForCut topologyArc C hmin) where
  frameCore := G.finite.frameCore
  extraNeighborCardTwo := G.finite.extraNeighborCardTwo

/-- Extract the positive cyclic-order row from a full finite Lemma 8 geometry
row, keyed to the non-cyclic neighbor data generated by the extracted reduced
frame/cardinality row. -/
def positiveOrderRowOfGeometryRow
    {n : Nat} {C : _root_.UDConfig n}
    {hmin : IsMinimalClearedFailure C}
    (G :
      PointwiseLemma8GeometryFields.{u}
        payForCut topologyArc C hmin) :
    M8PositiveCyclicOrderCertificate
      ((frameCoreRowOfGeometryRow
        (payForCut := payForCut) (topologyArc := topologyArc) G).extraNeighborData) where
  positiveCyclicOrderAt := G.finite.positiveCyclicOrderAt
  positiveCyclicOrder := G.finite.positiveCyclicOrder

/-- A full W20 Lemma 8 geometry source family contains exactly the remaining
frame/cardinality and positive cyclic-order families. -/
def exactPackageOfPointwiseSourceFamily
    (F : PointwiseW20Lemma8SourceFamily.{u} payForCut topologyArc) :
    ExactLemma8SourceRemainingPackage.{u} payForCut topologyArc where
  frameCore :=
    { row := fun C hmin =>
        frameCoreRowOfGeometryRow
          (payForCut := payForCut) (topologyArc := topologyArc)
          (F.row C hmin) }
  positiveOrder :=
    { row := fun C hmin =>
        positiveOrderRowOfGeometryRow
          (payForCut := payForCut) (topologyArc := topologyArc)
          (F.row C hmin) }

/-- The two W20 consumer spellings have the same exact remaining Lemma 8
package. -/
def exactPackageOfLedgerSourceFamily
    (F : LedgerW20Lemma8SourceFamily.{u} payForCut topologyArc) :
    ExactLemma8SourceRemainingPackage.{u} payForCut topologyArc :=
  exactPackageOfPointwiseSourceFamily
    (payForCut := payForCut) (topologyArc := topologyArc) F

theorem pointwiseSourceFamily_nonempty_iff_exactPackage :
    Nonempty (PointwiseW20Lemma8SourceFamily.{u} payForCut topologyArc) <->
      Nonempty (ExactLemma8SourceRemainingPackage.{u} payForCut topologyArc) := by
  constructor
  · intro h
    cases h with
    | intro F =>
        exact
          Nonempty.intro
            (exactPackageOfPointwiseSourceFamily
              (payForCut := payForCut) (topologyArc := topologyArc) F)
  · intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (pointwiseSourceFamilyOfExactPackage
              (payForCut := payForCut) (topologyArc := topologyArc) P)

theorem ledgerSourceFamily_nonempty_iff_exactPackage :
    Nonempty (LedgerW20Lemma8SourceFamily.{u} payForCut topologyArc) <->
      Nonempty (ExactLemma8SourceRemainingPackage.{u} payForCut topologyArc) :=
  pointwiseSourceFamily_nonempty_iff_exactPackage
    (payForCut := payForCut) (topologyArc := topologyArc)

/-- Conditional inhabitance of the Lemma 8 source family required by
`PointwiseProducerFamilyFieldsW20`. -/
theorem pointwiseSourceFamily_nonempty_of_exactPackage
    (P : ExactLemma8SourceRemainingPackage.{u} payForCut topologyArc) :
    Nonempty (PointwiseW20Lemma8SourceFamily.{u} payForCut topologyArc) :=
  (pointwiseSourceFamily_nonempty_iff_exactPackage
    (payForCut := payForCut) (topologyArc := topologyArc)).2
      (Nonempty.intro P)

/-- Conditional inhabitance of the Lemma 8 source family required by
`RemainingObligationLedgerW20`. -/
theorem ledgerSourceFamily_nonempty_of_exactPackage
    (P : ExactLemma8SourceRemainingPackage.{u} payForCut topologyArc) :
    Nonempty (LedgerW20Lemma8SourceFamily.{u} payForCut topologyArc) :=
  (ledgerSourceFamily_nonempty_iff_exactPackage
    (payForCut := payForCut) (topologyArc := topologyArc)).2
      (Nonempty.intro P)

@[simp]
theorem pointwiseSourceFamilyOfExactPackage_row_finite
    (P : ExactLemma8SourceRemainingPackage.{u} payForCut topologyArc)
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C) :
    (pointwiseSourceFamilyOfExactPackage
      (payForCut := payForCut) (topologyArc := topologyArc) P
        |>.row C hmin).finite =
      finiteGeometryPackageOfFrameCorePositiveOrder
        (payForCut := payForCut) (topologyArc := topologyArc)
        (P.frameCore.row C hmin) (P.positiveOrder.row C hmin) := by
  rfl

end

end Lemma8SourceInhabitationW21
end Swanepoel

namespace Verified

universe u

abbrev SwanepoelW21Lemma8ExactRemainingPackage
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u}) :
    Type (u + 1) :=
  Swanepoel.Lemma8SourceInhabitationW21.ExactLemma8SourceRemainingPackage.{u}
    payForCut topologyArc

theorem swanepoel_w21_pointwiseLemma8SourceFamily_nonempty_iff_exactPackage
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u}) :
    Nonempty
        (Swanepoel.Lemma8SourceInhabitationW21.PointwiseW20Lemma8SourceFamily.{u}
          payForCut topologyArc) <->
      Nonempty
        (SwanepoelW21Lemma8ExactRemainingPackage.{u}
          payForCut topologyArc) :=
  Swanepoel.Lemma8SourceInhabitationW21.pointwiseSourceFamily_nonempty_iff_exactPackage
    (payForCut := payForCut) (topologyArc := topologyArc)

theorem swanepoel_w21_ledgerLemma8SourceFamily_nonempty_iff_exactPackage
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u}) :
    Nonempty
        (Swanepoel.Lemma8SourceInhabitationW21.LedgerW20Lemma8SourceFamily.{u}
          payForCut topologyArc) <->
      Nonempty
        (SwanepoelW21Lemma8ExactRemainingPackage.{u}
          payForCut topologyArc) :=
  Swanepoel.Lemma8SourceInhabitationW21.ledgerSourceFamily_nonempty_iff_exactPackage
    (payForCut := payForCut) (topologyArc := topologyArc)

end Verified
end ErdosProblems1066
