import ErdosProblems1066.Swanepoel.Lemma8GeometryFieldsW18
import ErdosProblems1066.Swanepoel.PointwiseFamilyProducerW18

set_option autoImplicit false

/-!
# W19 concrete Lemma 8 geometry producer

This file is a row-level adapter from the W18 reduced Lemma 8 geometry fields
to the W16/W17 pointwise Lemma 8 producer surfaces.  It deliberately keeps the
finite geometric payload explicit: frame cores, exact extra-neighbor
cardinality two, and the cyclic-order predicate.
-/

namespace ErdosProblems1066
namespace Swanepoel
namespace Lemma8ConcreteGeometryProducerW19

open BoundaryTopologyArcBridgeW16
open CutVertexInterface
open Lemma8ExistenceConcrete
open Lemma8FiniteDataConstructionW17
open Lemma8ForbiddenDistinctConcrete
open Lemma8GeometryFieldsW18
open Lemma8LocalLabelsW16
open Lemma8NeighborExtractionConcrete
open M8LabelsFromBoundaryInterface
open MinimalFailureClosureW13
open MinimalGraphFacts
open PointwiseFamilyProducerW18
open PointwiseRemainingRowAssemblyW17

universe u

noncomputable section

variable
  (payForCut : PayForCutConcreteProducerFamily)
  (topologyArc : TopologyArcConcreteProducerFamily.{u})

variable {n : Nat} (C : _root_.UDConfig n)
variable (hmin : IsMinimalClearedFailure C)

/-- The exact pointwise spine selected by the W18 pay-for-cut and topology
producer rows. -/
def pointwiseSpine :
    M8BoundarySpine
      (M8BoundaryCutDegreeContext.of_minimalClearedFailure
        (topologyArc.row C hmin).arcBoundaryBudget.planarBoundary.core
        (MinimalFailureClosureW13.cutVertexOfNoCut hmin
          (payForCut.noCutVertex C hmin)).preconnectedNoCut hmin) :=
  MinimalFailureClosureW13.spineOfBoundaryArc hmin
    (payForCut.noCutVertex C hmin)
    (topologyArc.row C hmin).arcBoundaryBudget
    (topologyArc.row C hmin).boundaryArc

/-- The finite geometric payload that W18 proves sufficient for Lemma 8:
the reduced forbidden-frame core, exact two extra neighbors, and the remaining
cyclic-order datum. -/
structure PointwiseLemma8FiniteGeometryPackage
    (C : _root_.UDConfig n) (hmin : IsMinimalClearedFailure C) where
  frameCore :
    M8FourForbiddenFrameCore
      (pointwiseSpine payForCut topologyArc C hmin)
  extraNeighborCardTwo :
    forall i : M8ExtraIndex,
      (extraNeighborFinset
        (pointwiseSpine payForCut topologyArc C hmin) i).card = 2
  positiveCyclicOrderAt :
    M8ExtraIndex -> Fin n -> Fin n -> Fin n -> Fin n -> Fin n -> Fin n ->
      Prop
  positiveCyclicOrder :
    forall i : M8ExtraIndex,
      positiveCyclicOrderAt i
        ((extraNeighborDataOfFrameCoreAndExtraCardTwo
          frameCore extraNeighborCardTwo).s i)
        ((extraNeighborDataOfFrameCoreAndExtraCardTwo
          frameCore extraNeighborCardTwo).r i)
        ((pointwiseSpine payForCut topologyArc C hmin).prevQ i)
        ((pointwiseSpine payForCut topologyArc C hmin).leftP i)
        ((pointwiseSpine payForCut topologyArc C hmin).rightP i)
        ((pointwiseSpine payForCut topologyArc C hmin).nextQ i)

namespace PointwiseLemma8FiniteGeometryPackage

variable {payForCut topologyArc C hmin}

variable
  (P :
    PointwiseLemma8FiniteGeometryPackage.{u}
      payForCut topologyArc C hmin)

/-- The W18 reduced geometry-source package. -/
def toM8GeometryFieldSources :
    M8GeometryFieldSources
      (pointwiseSpine payForCut topologyArc C hmin) where
  frameCore := P.frameCore
  extraNeighborCardTwo := P.extraNeighborCardTwo
  positiveCyclicOrderAt := P.positiveCyclicOrderAt
  positiveCyclicOrder := P.positiveCyclicOrder

/-- The W17 degree-six field obtained from the finite geometry package. -/
def centerDegreeSix :
    forall i : M8ExtraIndex,
      centerDegree
        (pointwiseSpine payForCut topologyArc C hmin) i = 6 :=
  M8GeometryFieldSources.centerDegreeSix P.toM8GeometryFieldSources

/-- The W17 forbidden-frame field obtained from the finite geometry package. -/
def neighborFrame :
    forall i : M8ExtraIndex,
      FourForbiddenNeighborFrame
        (pointwiseSpine payForCut topologyArc C hmin) i :=
  M8GeometryFieldSources.forbiddenFrame P.toM8GeometryFieldSources

abbrev forbiddenFrame :
    forall i : M8ExtraIndex,
      FourForbiddenNeighborFrame
        (pointwiseSpine payForCut topologyArc C hmin) i :=
  P.neighborFrame

/-- The W17 extra-neighbor data generated by the finite package. -/
def extraNeighborData :
    M8ExtraNeighborData
      (pointwiseSpine payForCut topologyArc C hmin) :=
  M8GeometryFieldSources.extraNeighborData P.toM8GeometryFieldSources

/-- The W17 cyclic-order field in the concrete producer shape. -/
def positiveCyclicOrderForW17 :
    forall i : M8ExtraIndex,
      P.positiveCyclicOrderAt i
        ((M8ExtraNeighborData.ofDegreeSixForbiddenFrame
          P.centerDegreeSix P.neighborFrame).s i)
        ((M8ExtraNeighborData.ofDegreeSixForbiddenFrame
          P.centerDegreeSix P.neighborFrame).r i)
        ((pointwiseSpine payForCut topologyArc C hmin).prevQ i)
        ((pointwiseSpine payForCut topologyArc C hmin).leftP i)
        ((pointwiseSpine payForCut topologyArc C hmin).rightP i)
        ((pointwiseSpine payForCut topologyArc C hmin).nextQ i) :=
  P.positiveCyclicOrder

@[simp]
theorem toM8GeometryFieldSources_frameCore :
    P.toM8GeometryFieldSources.frameCore = P.frameCore :=
  rfl

@[simp]
theorem toM8GeometryFieldSources_extraNeighborCardTwo :
    P.toM8GeometryFieldSources.extraNeighborCardTwo =
      P.extraNeighborCardTwo :=
  rfl

@[simp]
theorem centerDegreeSix_eq :
    P.centerDegreeSix =
      M8GeometryFieldSources.centerDegreeSix P.toM8GeometryFieldSources :=
  rfl

@[simp]
theorem neighborFrame_eq :
    P.neighborFrame =
      M8GeometryFieldSources.forbiddenFrame P.toM8GeometryFieldSources :=
  rfl

theorem extraNeighborCardTwo_holds
    (Q :
      PointwiseLemma8FiniteGeometryPackage.{u}
        payForCut topologyArc C hmin)
    (i : M8ExtraIndex) :
    (extraNeighborFinset
      (pointwiseSpine payForCut topologyArc C hmin) i).card = 2 :=
  Q.extraNeighborCardTwo i

end PointwiseLemma8FiniteGeometryPackage

/-- Pointwise Lemma 8 geometry fields, in a form that remembers the finite
payload and therefore converts exactly to the W18 reducer and W16/W17 rows. -/
structure PointwiseLemma8GeometryFields
    (C : _root_.UDConfig n) (hmin : IsMinimalClearedFailure C) where
  finite :
    PointwiseLemma8FiniteGeometryPackage.{u}
      payForCut topologyArc C hmin

namespace PointwiseLemma8GeometryFields

variable {payForCut topologyArc C hmin}

variable
  (P :
    PointwiseLemma8GeometryFields.{u}
      payForCut topologyArc C hmin)

def toFiniteGeometryPackage :
    PointwiseLemma8FiniteGeometryPackage.{u}
      payForCut topologyArc C hmin :=
  P.finite

def toM8GeometryFieldSources :
    M8GeometryFieldSources
      (pointwiseSpine payForCut topologyArc C hmin) :=
  P.finite.toM8GeometryFieldSources

def centerDegreeSix :
    forall i : M8ExtraIndex,
      centerDegree
        (pointwiseSpine payForCut topologyArc C hmin) i = 6 :=
  P.finite.centerDegreeSix

def neighborFrame :
    forall i : M8ExtraIndex,
      FourForbiddenNeighborFrame
        (pointwiseSpine payForCut topologyArc C hmin) i :=
  P.finite.neighborFrame

abbrev forbiddenFrame :
    forall i : M8ExtraIndex,
      FourForbiddenNeighborFrame
        (pointwiseSpine payForCut topologyArc C hmin) i :=
  P.neighborFrame

def positiveCyclicOrderAt :
    M8ExtraIndex -> Fin n -> Fin n -> Fin n -> Fin n -> Fin n -> Fin n ->
      Prop :=
  P.finite.positiveCyclicOrderAt

def positiveCyclicOrder :
    forall i : M8ExtraIndex,
      P.positiveCyclicOrderAt i
        ((M8ExtraNeighborData.ofDegreeSixForbiddenFrame
          P.centerDegreeSix P.neighborFrame).s i)
        ((M8ExtraNeighborData.ofDegreeSixForbiddenFrame
          P.centerDegreeSix P.neighborFrame).r i)
        ((pointwiseSpine payForCut topologyArc C hmin).prevQ i)
        ((pointwiseSpine payForCut topologyArc C hmin).leftP i)
        ((pointwiseSpine payForCut topologyArc C hmin).rightP i)
        ((pointwiseSpine payForCut topologyArc C hmin).nextQ i) :=
  P.finite.positiveCyclicOrderForW17

def lemma8Combinatorics :
    M8Lemma8Combinatorics
      (pointwiseSpine payForCut topologyArc C hmin) :=
  P.toM8GeometryFieldSources.toLemma8Combinatorics

def lemma8Existence :
    M8Lemma8MissingExistenceConditions
      (pointwiseSpine payForCut topologyArc C hmin) :=
  P.toM8GeometryFieldSources.toMissingExistenceConditions

/-- Convert the pointwise geometry row to the W16 local-label input row. -/
def toPointwiseLemma8LocalLabelInputs :
    PointwiseLemma8LocalLabelInputs.{u} C hmin where
  noCutVertex := payForCut.noCutVertex C hmin
  arcBoundaryBudget := (topologyArc.row C hmin).arcBoundaryBudget
  boundaryArc := (topologyArc.row C hmin).boundaryArc
  centerDegreeSix := P.centerDegreeSix
  neighborFrame := P.neighborFrame
  positiveCyclicOrderAt := P.positiveCyclicOrderAt
  positiveCyclicOrder := P.positiveCyclicOrder

/-- Convert the pointwise geometry row to the W16 base input row used by the
remaining pointwise assembly. -/
def toPointwiseW16BaseInputs :
    PointwiseW16BaseInputs.{u} C hmin where
  minimalitySelectedPayForCut :=
    payForCut.minimalitySelectedPayForCut C hmin
  topologyArc := topologyArc.row C hmin
  centerDegreeSix := P.centerDegreeSix
  neighborFrame := P.neighborFrame
  positiveCyclicOrderAt := P.positiveCyclicOrderAt
  positiveCyclicOrder := P.positiveCyclicOrder

def localLabels :
    M8ConstructionInterface.M8LocalLabels C :=
  P.toPointwiseLemma8LocalLabelInputs.localLabels

@[simp]
theorem toPointwiseLemma8LocalLabelInputs_boundaryArc :
    P.toPointwiseLemma8LocalLabelInputs.boundaryArc =
      (topologyArc.row C hmin).boundaryArc :=
  rfl

@[simp]
theorem toPointwiseLemma8LocalLabelInputs_centerDegreeSix :
    P.toPointwiseLemma8LocalLabelInputs.centerDegreeSix =
      P.centerDegreeSix :=
  rfl

@[simp]
theorem toPointwiseLemma8LocalLabelInputs_neighborFrame :
    P.toPointwiseLemma8LocalLabelInputs.neighborFrame =
      P.neighborFrame :=
  rfl

@[simp]
theorem toPointwiseW16BaseInputs_topologyArc :
    P.toPointwiseW16BaseInputs.topologyArc =
      topologyArc.row C hmin :=
  rfl

@[simp]
theorem toPointwiseW16BaseInputs_centerDegreeSix :
    P.toPointwiseW16BaseInputs.centerDegreeSix =
      P.centerDegreeSix :=
  rfl

@[simp]
theorem toPointwiseW16BaseInputs_neighborFrame :
    P.toPointwiseW16BaseInputs.neighborFrame =
      P.neighborFrame :=
  rfl

theorem localLabels_extraNeighborWitness (i : M8ExtraIndex) :
    P.localLabels.predicates.data.extraNeighborWitness i :=
  P.toPointwiseLemma8LocalLabelInputs.localLabels_extraNeighborWitness i

end PointwiseLemma8GeometryFields

theorem pointwiseLemma8GeometryFields_iff_finiteGeometryPackage :
    Nonempty
        (PointwiseLemma8GeometryFields.{u}
          payForCut topologyArc C hmin) <->
      Nonempty
        (PointwiseLemma8FiniteGeometryPackage.{u}
          payForCut topologyArc C hmin) := by
  constructor
  · intro h
    cases h with
    | intro P =>
        exact Nonempty.intro P.finite
  · intro h
    cases h with
    | intro P =>
        exact Nonempty.intro { finite := P }

/-- A uniform family of pointwise Lemma 8 geometry rows for fixed concrete
pay-for-cut and topology-arc producer families. -/
structure PointwiseLemma8GeometryFieldFamily : Type (u + 1) where
  row :
    forall {n : Nat} (C : _root_.UDConfig n)
      (hmin : IsMinimalClearedFailure C),
        PointwiseLemma8GeometryFields.{u}
          payForCut topologyArc C hmin

namespace PointwiseLemma8GeometryFieldFamily

variable {payForCut topologyArc}

variable
  (F : PointwiseLemma8GeometryFieldFamily.{u}
    payForCut topologyArc)

/-- The W18 `PointwiseFamilyProducerW18` Lemma 8 producer assembled from the
exact finite geometry rows. -/
def toLemma8ConcreteProducerFamily :
    Lemma8ConcreteProducerFamily.{u} payForCut topologyArc where
  centerDegreeSix := fun C hmin =>
    (F.row C hmin).centerDegreeSix
  neighborFrame := fun C hmin =>
    (F.row C hmin).neighborFrame
  positiveCyclicOrderAt := fun C hmin =>
    (F.row C hmin).positiveCyclicOrderAt
  positiveCyclicOrder := fun C hmin =>
    (F.row C hmin).positiveCyclicOrder

def toPointwiseW16BaseInputs
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C) :
    PointwiseW16BaseInputs.{u} C hmin :=
  (F.row C hmin).toPointwiseW16BaseInputs

def toPointwiseLemma8LocalLabelInputs
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C) :
    PointwiseLemma8LocalLabelInputs.{u} C hmin :=
  (F.row C hmin).toPointwiseLemma8LocalLabelInputs

@[simp]
theorem toLemma8ConcreteProducerFamily_centerDegreeSix
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C) :
    F.toLemma8ConcreteProducerFamily.centerDegreeSix C hmin =
      (F.row C hmin).centerDegreeSix :=
  rfl

@[simp]
theorem toLemma8ConcreteProducerFamily_neighborFrame
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C) :
    F.toLemma8ConcreteProducerFamily.neighborFrame C hmin =
      (F.row C hmin).neighborFrame :=
  rfl

@[simp]
theorem toLemma8ConcreteProducerFamily_positiveCyclicOrderAt
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : IsMinimalClearedFailure C) :
    F.toLemma8ConcreteProducerFamily.positiveCyclicOrderAt C hmin =
      (F.row C hmin).positiveCyclicOrderAt :=
  rfl

theorem nonempty_lemma8ConcreteProducerFamily
    (F : PointwiseLemma8GeometryFieldFamily.{u}
      payForCut topologyArc) :
    Nonempty (Lemma8ConcreteProducerFamily.{u} payForCut topologyArc) :=
  Nonempty.intro (toLemma8ConcreteProducerFamily F)

end PointwiseLemma8GeometryFieldFamily

theorem lemma8ConcreteProducerFamily_of_geometryFieldFamily
    (F : PointwiseLemma8GeometryFieldFamily.{u}
      payForCut topologyArc) :
    Nonempty (Lemma8ConcreteProducerFamily.{u} payForCut topologyArc) :=
  PointwiseLemma8GeometryFieldFamily.nonempty_lemma8ConcreteProducerFamily F

end

end Lemma8ConcreteGeometryProducerW19
end Swanepoel
end ErdosProblems1066
