import ErdosProblems1066.Swanepoel.Lemma8GeometryFamilyConcreteW27

set_option autoImplicit false
set_option linter.unusedDecidableInType false

/-!
# W28 Lemma 8 finite geometry rows

This file isolates the exact pointwise finite row still needed by the W27
Lemma 8 geometry-family bridge.  The row is the reduced frame/cardinality
payload together with the positive cyclic-order certificate for the concrete
extra-neighbor data generated by that payload.

No endpoint or geometric existence theorem is introduced here.
-/

namespace ErdosProblems1066
namespace Swanepoel
namespace Lemma8FiniteGeometryRowsW28

open BoundaryFrameCoreProducerW19
open Lemma8ConcreteGeometryProducerW19
open Lemma8NeighborExtractionConcrete
open MinimalGraphFacts
open PointwiseFamilyProducerW18
open PositiveCyclicOrderProducerW19

universe u

noncomputable section

variable
  (payForCut : PayForCutConcreteProducerFamily)
  (topologyArc : TopologyArcConcreteProducerFamily.{u})

variable {n : Nat} (C : _root_.UDConfig n)
variable (hmin : IsMinimalClearedFailure C)

abbrev PointwiseSpine :=
  pointwiseSpine payForCut topologyArc C hmin

abbrev FrameCardinalityRow : Prop :=
  Lemma8GeometryFamilyConcreteW27.PointwiseFrameCardinalityRow.{u}
    payForCut topologyArc C hmin

abbrev PositiveOrderRow
    (R : FrameCardinalityRow.{u} payForCut topologyArc C hmin) : Type :=
  Lemma8GeometryFamilyConcreteW27.PointwisePositiveOrderRow.{u}
    payForCut topologyArc C hmin R

abbrev NeighborCyclicOrderRow
    (R : FrameCardinalityRow.{u} payForCut topologyArc C hmin) : Type :=
  M8ExtraNeighborData.CyclicOrder R.extraNeighborData

abbrev GeometryNonorderRow : Prop :=
  PositiveCyclicOrderProducerW19.M8GeometryNonorderSources
    (PointwiseSpine payForCut topologyArc C hmin)

abbrev FiniteGeometryPackage : Type :=
  Lemma8GeometryFamilyConcreteW27.PointwiseFiniteGeometryPackage.{u}
    payForCut topologyArc C hmin

abbrev PointwiseGeometryFields : Type :=
  Lemma8GeometryFamilyConcreteW27.PointwiseGeometryFields.{u}
    payForCut topologyArc C hmin

/-- The row-level package: frame/cardinality data plus the positive order
certificate keyed to exactly the generated non-cyclic neighbor data. -/
structure FiniteGeometryRows : Type where
  frameCardinality :
    FrameCardinalityRow.{u} payForCut topologyArc C hmin
  positiveOrder :
    PositiveOrderRow.{u}
      payForCut topologyArc C hmin frameCardinality

def geometryNonorderRowOfFrameCardinalityRow
    (R : FrameCardinalityRow.{u} payForCut topologyArc C hmin) :
    GeometryNonorderRow payForCut topologyArc C hmin where
  frameCore := R.frameCore
  extraNeighborCardTwo := R.extraNeighborCardTwo

def frameCardinalityRowOfGeometryNonorderRow
    (G : GeometryNonorderRow payForCut topologyArc C hmin) :
    FrameCardinalityRow.{u} payForCut topologyArc C hmin where
  frameCore := G.frameCore
  extraNeighborCardTwo := G.extraNeighborCardTwo

theorem frameCardinalityRow_nonempty_iff_geometryNonorderRow :
    Nonempty (FrameCardinalityRow.{u} payForCut topologyArc C hmin) <->
      Nonempty (GeometryNonorderRow payForCut topologyArc C hmin) := by
  constructor
  case mp =>
    intro h
    cases h with
    | intro R =>
        exact
          Nonempty.intro
            (geometryNonorderRowOfFrameCardinalityRow
              (payForCut := payForCut) (topologyArc := topologyArc)
              C hmin R)
  case mpr =>
    intro h
    cases h with
    | intro G =>
        exact
          Nonempty.intro
            (frameCardinalityRowOfGeometryNonorderRow
              (payForCut := payForCut) (topologyArc := topologyArc)
              C hmin G)

def neighborCyclicOrderRowOfPositiveOrderRow
    {R : FrameCardinalityRow.{u} payForCut topologyArc C hmin}
    (O : PositiveOrderRow.{u} payForCut topologyArc C hmin R) :
    NeighborCyclicOrderRow payForCut topologyArc C hmin R :=
  O.toNeighborCyclicOrder

def positiveOrderRowOfNeighborCyclicOrderRow
    {R : FrameCardinalityRow.{u} payForCut topologyArc C hmin}
    (O : NeighborCyclicOrderRow payForCut topologyArc C hmin R) :
    PositiveOrderRow.{u} payForCut topologyArc C hmin R :=
  M8PositiveCyclicOrderCertificate.ofNeighborCyclicOrder O

theorem positiveOrderRow_nonempty_iff_neighborCyclicOrderRow
    (R : FrameCardinalityRow.{u} payForCut topologyArc C hmin) :
    Nonempty
        (PositiveOrderRow.{u} payForCut topologyArc C hmin R) <->
      Nonempty
        (NeighborCyclicOrderRow payForCut topologyArc C hmin R) :=
  M8PositiveCyclicOrderCertificate.nonempty_iff_neighborCyclicOrder

def finiteGeometryPackageOfRows
    (P : FiniteGeometryRows.{u} payForCut topologyArc C hmin) :
    FiniteGeometryPackage.{u} payForCut topologyArc C hmin :=
  Lemma8GeometryFamilyConcreteW27.finiteGeometryPackageOfFrameCardinalityPositiveOrder
    (payForCut := payForCut) (topologyArc := topologyArc)
    C hmin P.frameCardinality P.positiveOrder

def pointwiseGeometryFieldsOfRows
    (P : FiniteGeometryRows.{u} payForCut topologyArc C hmin) :
    PointwiseGeometryFields.{u} payForCut topologyArc C hmin where
  finite :=
    finiteGeometryPackageOfRows
      (payForCut := payForCut) (topologyArc := topologyArc)
      C hmin P

def rowsOfFiniteGeometryPackage
    (P : FiniteGeometryPackage.{u} payForCut topologyArc C hmin) :
    FiniteGeometryRows.{u} payForCut topologyArc C hmin where
  frameCardinality :=
    Lemma8GeometryFamilyConcreteW27.frameCardinalityRowOfFiniteGeometryPackage
      (payForCut := payForCut) (topologyArc := topologyArc)
      C hmin P
  positiveOrder :=
    Lemma8GeometryFamilyConcreteW27.positiveOrderRowOfFiniteGeometryPackage
      (payForCut := payForCut) (topologyArc := topologyArc)
      C hmin P

def rowsOfPointwiseGeometryFields
    (P : PointwiseGeometryFields.{u} payForCut topologyArc C hmin) :
    FiniteGeometryRows.{u} payForCut topologyArc C hmin :=
  rowsOfFiniteGeometryPackage
    (payForCut := payForCut) (topologyArc := topologyArc)
    C hmin P.finite

theorem finiteGeometryRows_nonempty_iff_frameCardinality_positiveOrder :
    Nonempty (FiniteGeometryRows.{u} payForCut topologyArc C hmin) <->
      exists R : FrameCardinalityRow.{u} payForCut topologyArc C hmin,
        Nonempty
          (PositiveOrderRow.{u} payForCut topologyArc C hmin R) := by
  constructor
  case mp =>
    intro h
    cases h with
    | intro P =>
        exact Exists.intro P.frameCardinality (Nonempty.intro P.positiveOrder)
  case mpr =>
    intro h
    cases h with
    | intro R hO =>
        cases hO with
        | intro O =>
            exact Nonempty.intro { frameCardinality := R, positiveOrder := O }

theorem finiteGeometryPackage_nonempty_iff_rows :
    Nonempty (FiniteGeometryPackage.{u} payForCut topologyArc C hmin) <->
      Nonempty (FiniteGeometryRows.{u} payForCut topologyArc C hmin) := by
  constructor
  case mp =>
    intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (rowsOfFiniteGeometryPackage
              (payForCut := payForCut) (topologyArc := topologyArc)
              C hmin P)
  case mpr =>
    intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (finiteGeometryPackageOfRows
              (payForCut := payForCut) (topologyArc := topologyArc)
              C hmin P)

theorem finiteGeometryPackage_nonempty_iff_frameCardinality_positiveOrder :
    Nonempty (FiniteGeometryPackage.{u} payForCut topologyArc C hmin) <->
      exists R : FrameCardinalityRow.{u} payForCut topologyArc C hmin,
        Nonempty
          (PositiveOrderRow.{u} payForCut topologyArc C hmin R) := by
  exact
    (finiteGeometryPackage_nonempty_iff_rows
      (payForCut := payForCut) (topologyArc := topologyArc)
      C hmin).trans
      (finiteGeometryRows_nonempty_iff_frameCardinality_positiveOrder
        (payForCut := payForCut) (topologyArc := topologyArc)
        C hmin)

theorem pointwiseGeometryFields_nonempty_iff_rows :
    Nonempty (PointwiseGeometryFields.{u} payForCut topologyArc C hmin) <->
      Nonempty (FiniteGeometryRows.{u} payForCut topologyArc C hmin) := by
  constructor
  case mp =>
    intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (rowsOfPointwiseGeometryFields
              (payForCut := payForCut) (topologyArc := topologyArc)
              C hmin P)
  case mpr =>
    intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (pointwiseGeometryFieldsOfRows
              (payForCut := payForCut) (topologyArc := topologyArc)
              C hmin P)

theorem pointwiseGeometryFields_nonempty_iff_frameCardinality_positiveOrder :
    Nonempty (PointwiseGeometryFields.{u} payForCut topologyArc C hmin) <->
      exists R : FrameCardinalityRow.{u} payForCut topologyArc C hmin,
        Nonempty
          (PositiveOrderRow.{u} payForCut topologyArc C hmin R) := by
  exact
    (pointwiseGeometryFields_nonempty_iff_rows
      (payForCut := payForCut) (topologyArc := topologyArc)
      C hmin).trans
      (finiteGeometryRows_nonempty_iff_frameCardinality_positiveOrder
        (payForCut := payForCut) (topologyArc := topologyArc)
        C hmin)

/-! ## Uniform finite rows feeding the W27 family bridge -/

structure UniformFiniteGeometryRows : Type (u + 1) where
  row :
    forall {n : Nat} (C : _root_.UDConfig n)
      (hmin : IsMinimalClearedFailure C),
        FiniteGeometryRows.{u} payForCut topologyArc C hmin

abbrev ExactRemainingPackage : Type (u + 1) :=
  Lemma8GeometryFamilyConcreteW27.ExactRemainingPackage.{u}
    payForCut topologyArc

abbrev GeometryFieldFamily : Type (u + 1) :=
  Lemma8GeometryFamilyConcreteW27.GeometryFieldFamily.{u}
    payForCut topologyArc

def exactRemainingPackageOfUniformRows
    (P : UniformFiniteGeometryRows.{u} payForCut topologyArc) :
    ExactRemainingPackage.{u} payForCut topologyArc where
  frameCore := { row := fun C hmin => (P.row C hmin).frameCardinality }
  positiveOrder := { row := fun C hmin => (P.row C hmin).positiveOrder }

def uniformRowsOfExactRemainingPackage
    (P : ExactRemainingPackage.{u} payForCut topologyArc) :
    UniformFiniteGeometryRows.{u} payForCut topologyArc where
  row := fun C hmin =>
    { frameCardinality := P.frameCore.row C hmin
      positiveOrder := P.positiveOrder.row C hmin }

def geometryFieldFamilyOfUniformRows
    (P : UniformFiniteGeometryRows.{u} payForCut topologyArc) :
    GeometryFieldFamily.{u} payForCut topologyArc :=
  Lemma8GeometryFamilyConcreteW27.geometryFieldFamilyOfExactRemainingPackage
    (payForCut := payForCut) (topologyArc := topologyArc)
    (exactRemainingPackageOfUniformRows
      (payForCut := payForCut) (topologyArc := topologyArc) P)

theorem uniformFiniteGeometryRows_nonempty_iff_exactRemainingPackage :
    Nonempty (UniformFiniteGeometryRows.{u} payForCut topologyArc) <->
      Nonempty (ExactRemainingPackage.{u} payForCut topologyArc) := by
  constructor
  case mp =>
    intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (exactRemainingPackageOfUniformRows
              (payForCut := payForCut) (topologyArc := topologyArc) P)
  case mpr =>
    intro h
    cases h with
    | intro P =>
        exact
          Nonempty.intro
            (uniformRowsOfExactRemainingPackage
              (payForCut := payForCut) (topologyArc := topologyArc) P)

theorem geometryFieldFamily_nonempty_of_uniformRows
    (P : UniformFiniteGeometryRows.{u} payForCut topologyArc) :
    Nonempty (GeometryFieldFamily.{u} payForCut topologyArc) :=
  Nonempty.intro
    (geometryFieldFamilyOfUniformRows
      (payForCut := payForCut) (topologyArc := topologyArc) P)

theorem geometryFieldFamily_nonempty_iff_uniformFiniteGeometryRows :
    Nonempty (GeometryFieldFamily.{u} payForCut topologyArc) <->
      Nonempty (UniformFiniteGeometryRows.{u} payForCut topologyArc) := by
  exact
    (Lemma8FrameOrderConcreteW23.exactPackage_nonempty_iff_geometryFieldFamily
      (payForCut := payForCut) (topologyArc := topologyArc)).symm.trans
      (uniformFiniteGeometryRows_nonempty_iff_exactRemainingPackage
        (payForCut := payForCut) (topologyArc := topologyArc)).symm

end

end Lemma8FiniteGeometryRowsW28
end Swanepoel

namespace Verified

universe u

abbrev SwanepoelW28Lemma8FiniteGeometryRows
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u})
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : Swanepoel.MinimalGraphFacts.IsMinimalClearedFailure C) :
    Type :=
  Swanepoel.Lemma8FiniteGeometryRowsW28.FiniteGeometryRows.{u}
    payForCut topologyArc C hmin

abbrev SwanepoelW28Lemma8UniformFiniteGeometryRows
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u}) :
    Type (u + 1) :=
  Swanepoel.Lemma8FiniteGeometryRowsW28.UniformFiniteGeometryRows.{u}
    payForCut topologyArc

theorem swanepoel_w28_lemma8FiniteGeometryPackage_nonempty_iff_rows
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u})
    {n : Nat} (C : _root_.UDConfig n)
    (hmin : Swanepoel.MinimalGraphFacts.IsMinimalClearedFailure C) :
    Nonempty
        (Swanepoel.Lemma8GeometryFamilyConcreteW27.PointwiseFiniteGeometryPackage.{u}
          payForCut topologyArc C hmin) <->
      Nonempty
        (SwanepoelW28Lemma8FiniteGeometryRows.{u}
          payForCut topologyArc C hmin) :=
  Swanepoel.Lemma8FiniteGeometryRowsW28.finiteGeometryPackage_nonempty_iff_rows
    (payForCut := payForCut) (topologyArc := topologyArc)
    C hmin

theorem swanepoel_w28_lemma8GeometryFieldFamily_nonempty_iff_uniformFiniteRows
    (payForCut :
      Swanepoel.PointwiseFamilyProducerW18.PayForCutConcreteProducerFamily)
    (topologyArc :
      Swanepoel.PointwiseFamilyProducerW18.TopologyArcConcreteProducerFamily.{u}) :
    Nonempty
        (Swanepoel.Lemma8GeometryFamilyConcreteW27.GeometryFieldFamily.{u}
          payForCut topologyArc) <->
      Nonempty
        (SwanepoelW28Lemma8UniformFiniteGeometryRows.{u}
          payForCut topologyArc) :=
  Swanepoel.Lemma8FiniteGeometryRowsW28.geometryFieldFamily_nonempty_iff_uniformFiniteGeometryRows
    (payForCut := payForCut) (topologyArc := topologyArc)

end Verified
end ErdosProblems1066
